
[[language]]
name = "python"
auto-format = false
[language.formatter]
command = "black"
args = [
"-", # stdin
"--quiet",
"--line-length=79",
]

[[language]]
name = "markdown"
formatter = { command = 'prettier', args = ["--parser", "markdown"] }


